name: CI

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]
  workflow_dispatch:

jobs:
  build_and_run_docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Build Docker image
        run: docker build -t carbonara-recipe-calculator .

      - name: Run Docker container
        run: docker run carbonara-recipe-calculator sh -c "echo 'Running container for 60 seconds...'; sleep 60"
