name: CI

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify your Python version here

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Replace with your dependencies if needed

      - name: Check code style with Black
        run: |
          pip install black
          black --check .  # Replace '.' with the directory containing your Python files

      - name: Run tests  # Replace with your test commands
        run: |
          pytest
